name: parse_large_file_sde
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
  smedahidesdex:
    path: ../../../../spreadsheet_data_extractor

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0