name: parse_large_sheet_sde
version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
  spreadsheet_data_extractor:
    path: ../../../spreadsheet_data_extractor

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0